export const BRANDS = [
  { name: 'BMW', color: '#0066B1', slug: 'bmw' },
  { name: 'Mercedes-Benz', color: '#0A1E2E', slug: null },
  { name: 'Audi', color: '#BB0A30', slug: 'audi' },
  { name: 'Volkswagen', color: '#1A1A1A', slug: 'volkswagen' },
  { name: 'Porsche', color: '#B12B28', slug: 'porsche' },
  { name: 'Toyota', color: '#EB0A1E', slug: 'toyota' },
  { name: 'Honda', color: '#CC0000', slug: 'honda' },
  { name: 'Hyundai', color: '#002C5F', slug: 'hyundai' },
  { name: 'Kia', color: '#BB162B', slug: 'kia' },
  { name: 'Ford', color: '#003478', slug: 'ford' },
  { name: 'Opel', color: '#F1D315', slug: 'opel' },
  { name: 'Renault', color: '#FFC300', slug: 'renault' },
  { name: 'Peugeot', color: '#000000', slug: 'peugeot' },
  { name: 'Tesla', color: '#CC0000', slug: 'tesla' },
  { name: 'Volvo', color: '#003057', slug: 'volvo' },
  { name: 'Nissan', color: '#C3002F', slug: 'nissan' },
  { name: 'Citroën', color: '#DA291C', slug: 'citroen' },
  { name: 'Fiat', color: '#0066B1', slug: 'fiat' },
  { name: 'Škoda', color: '#008000', slug: 'skoda' },
  { name: 'Seat', color: '#D50032', slug: 'seat' },
  { name: 'Dacia', color: '#007979', slug: 'dacia' },
  { name: 'Mazda', color: '#C8121A', slug: 'mazda' },
  { name: 'Suzuki', color: '#003B8E', slug: 'suzuki' },
  { name: 'Land Rover', color: '#006B54', slug: null },
  { name: 'Jeep', color: '#1A1A1A', slug: 'jeep' },
  { name: 'Mini', color: '#2E6E3E', slug: 'mini' },
  { name: 'Lexus', color: '#1B1B1B', slug: null },
  { name: 'Alfa Romeo', color: '#003B6F', slug: null },
];

export const HOME_BRANDS = [
  'BMW',
  'Mercedes-Benz',
  'Audi',
  'Volkswagen',
  'Porsche',
  'Toyota',
  'Honda',
  'Hyundai',
  'Kia',
  'Ford',
  'Renault',
  'Tesla',
]
  .map((n) => BRANDS.find((b) => b.name === n))
  .filter(Boolean);
